export const ORDER_SIZES = {
  SMALL: 'S',
  MEDIUM: 'M',
  LARGE: 'L',
  EXTRA_LARGE: 'EL',
};

export const ORDER_ACTION_TYPES = {
  ADD_ITEM: 'ADD_ITEM',
  REMOVE_ITEM: 'REMOVE_ITEM',
  UPDATE_TIME: 'UPDATE_TIME',
  SET_TOTAL_WITH_TAX: 'SET_TOTAL_WITH_TAX',
  UPDATE_PHONE_NUMBER: 'UPDATE_PHONE_NUMBER',
  SUBMIT_ORDER: 'SUBMIT_ORDER',
  CLEAR_ORDER: 'CLEAR_ORDER',
  SET_ORDER: 'SET_ORDER',
  SET_TIME: 'SET_TIME',
};
